# 1. Import and Install Dependencies

In [1]:
!pip install tensorflow opencv-python mediapipe sklearn matplotlib

In [2]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp

# 2. Keypoints using MP Holistic

In [11]:
mp_holistic = mp.solutions.holistic # Holistic model
mp_drawing = mp.solutions.drawing_utils # Drawing utilities

In [12]:
def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # COLOR CONVERSION BGR 2 RGB
    image.flags.writeable = False                  # Image is no longer writeable
    results = model.process(image)                 # Make prediction
    image.flags.writeable = True                   # Image is now writeable 
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR) # COLOR COVERSION RGB 2 BGR
    return image, results

In [13]:
def draw_landmarks(image, results):
    #mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION) # Draw face connections
    #mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS) # Draw pose connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw right hand connections

In [14]:
def draw_styled_landmarks(image, results):
    # Draw face connections
    #mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION, 
    #                         mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), 
    #                         mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
    #                         ) 
    # Draw pose connections
#     mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
#                              mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4), 
#                              mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
#                              ) 
    # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                             ) 
    # Draw right hand connections  
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                             ) 

In [25]:
cap = cv2.VideoCapture(1)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()
        cap.set(3, 1280)
        cap.set(4, 720)
        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)

        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [16]:
cap.release()
cv2.destroyAllWindows()

In [23]:
draw_landmarks(frame, results)

In [24]:
plt.imshow(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))

error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


# 3. Extract Keypoint Values

In [11]:
len(results.left_hand_landmarks.landmark)

21

In [12]:
pose = []
for res in results.pose_landmarks.landmark:
    test = np.array([res.x, res.y, res.z, res.visibility])
    pose.append(test)

In [13]:
#+pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(132)
#face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)
lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)

In [16]:
face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() 
    if results.face_landmarks 
    else np.zeros(1404)


IndentationError: unexpected indent (1373052555.py, line 2)

In [14]:
def extract_keypoints(results):
    #pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33*4)
    #face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)
    lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
    #return np.concatenate([pose, face, lh, rh])
    return np.concatenate([lh, rh])

In [15]:
result_test = extract_keypoints(results)

In [16]:
result_test

array([ 8.12938154e-01,  6.79658055e-01, -2.88264488e-07,  7.60304928e-01,
        6.93328738e-01,  1.10353427e-02,  7.22395897e-01,  6.73487723e-01,
        2.27974709e-02,  6.94189847e-01,  6.46570146e-01,  2.76505258e-02,
        6.69048011e-01,  6.26690984e-01,  3.22231464e-02,  7.69013226e-01,
        5.68666160e-01,  5.80531769e-02,  7.38269031e-01,  5.35479665e-01,
        6.91843629e-02,  7.12127984e-01,  5.20217717e-01,  6.43764660e-02,
        6.89921439e-01,  5.09067893e-01,  5.78947142e-02,  7.77448297e-01,
        5.40888548e-01,  4.89099063e-02,  7.40226448e-01,  4.97865379e-01,
        6.14155456e-02,  7.09597945e-01,  4.79612887e-01,  5.03598191e-02,
        6.86724007e-01,  4.76124108e-01,  3.87216471e-02,  7.89782405e-01,
        5.16331613e-01,  3.69512998e-02,  7.57536232e-01,  4.66155648e-01,
        4.70096283e-02,  7.26646006e-01,  4.50646430e-01,  3.64784598e-02,
        7.02120006e-01,  4.51993644e-01,  2.62910649e-02,  8.05782378e-01,
        4.94920611e-01,  

In [17]:
np.save('0', result_test)

In [18]:
np.load('0.npy')

array([ 8.12938154e-01,  6.79658055e-01, -2.88264488e-07,  7.60304928e-01,
        6.93328738e-01,  1.10353427e-02,  7.22395897e-01,  6.73487723e-01,
        2.27974709e-02,  6.94189847e-01,  6.46570146e-01,  2.76505258e-02,
        6.69048011e-01,  6.26690984e-01,  3.22231464e-02,  7.69013226e-01,
        5.68666160e-01,  5.80531769e-02,  7.38269031e-01,  5.35479665e-01,
        6.91843629e-02,  7.12127984e-01,  5.20217717e-01,  6.43764660e-02,
        6.89921439e-01,  5.09067893e-01,  5.78947142e-02,  7.77448297e-01,
        5.40888548e-01,  4.89099063e-02,  7.40226448e-01,  4.97865379e-01,
        6.14155456e-02,  7.09597945e-01,  4.79612887e-01,  5.03598191e-02,
        6.86724007e-01,  4.76124108e-01,  3.87216471e-02,  7.89782405e-01,
        5.16331613e-01,  3.69512998e-02,  7.57536232e-01,  4.66155648e-01,
        4.70096283e-02,  7.26646006e-01,  4.50646430e-01,  3.64784598e-02,
        7.02120006e-01,  4.51993644e-01,  2.62910649e-02,  8.05782378e-01,
        4.94920611e-01,  

# 4. Setup Folders for Collection

In [157]:
# Path for exported data, numpy arrays
DATA_PATH = os.path.join('MP_Data') 

# Actions that we try to detect
actions = np.array(['lock_person', 'unlock_person', 'follow', 'stop', 'go_to_base', 'turn_left', 'turn_right', 'move_forward', 'move_backword'])


# Thirty videos worth of data
no_sequences = 30

# Videos are going to be 30 frames in length
sequence_length = 60

# Folder start
start_folder = 0

In [159]:
for action in actions: 
    for sequence in range(1,no_sequences+1):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
        except:
            pass

In [158]:
for action in actions: 
    dirmax = np.max(np.array(os.listdir(os.path.join(DATA_PATH, action))).astype(int))
    for sequence in range(1,no_sequences+1):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(dirmax+sequence)))
        except:
            pass

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'MP_Data\\lock_person'

# 5. Collect Keypoint Values for Training and Testing

In [44]:
cap = cv2.VideoCapture(3)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    
    # NEW LOOP
    # Loop through actions
    for action in actions:
        # Loop through sequences aka videos
        for sequence in range(start_folder, start_folder+no_sequences):
            # Loop through video length aka sequence length
            for frame_num in range(sequence_length):

                # Read feed
                ret, frame = cap.read()

                # Make detections
                image, results = mediapipe_detection(frame, holistic)

                # Draw landmarks
                draw_styled_landmarks(image, results)
                
                # NEW Apply wait logic
                if frame_num == 0: 
                    cv2.putText(image, 'STARTING COLLECTION', (120,200), 
                               cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                    cv2.waitKey(2000) # defines the wait time between collection
                else: 
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                
                # NEW Export keypoints
                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
                np.save(npy_path, keypoints)

                # Break gracefully
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
                    
    cap.release()
    cv2.destroyAllWindows()

In [164]:
cap.release()
cv2.destroyAllWindows()

# 6. Preprocess Data and Create Labels and Features

In [165]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [166]:
label_map = {label:num for num, label in enumerate(actions)}

In [167]:
label_map

{'lock_person': 0,
 'unlock_person': 1,
 'follow': 2,
 'stop': 3,
 'go_to_base': 4,
 'turn_left': 5,
 'turn_right': 6,
 'move_forward': 7,
 'move_backword': 8}

In [168]:
sequences, labels = [], []
for action in actions:
    for sequence in np.array(os.listdir(os.path.join(DATA_PATH, action))).astype(int):
        window = []
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [169]:
np.array(sequences).shape

(270, 60, 258)

In [170]:
np.array(labels).shape

(270,)

In [171]:
X = np.array(sequences)

In [172]:
X.shape

(270, 60, 258)

In [173]:
y = to_categorical(labels).astype(int)

In [174]:
y

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [175]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)

In [176]:
y_test.shape

(14, 9)

# 7. Build and Train LSTM Neural Network

In [177]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard

In [126]:
log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

In [178]:
model = Sequential()
model.add(LSTM(128, return_sequences=True, activation='relu', input_shape=(60,258)))
model.add(LSTM(256, return_sequences=True, activation='relu'))
model.add(LSTM(128, return_sequences=False, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))

In [179]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [180]:
model.fit(X_train, y_train, epochs=2000, callbacks=[tb_callback])

Epoch 1/2000
8/8 [==============================] - 5s 231ms/step - loss: 2.2915 - categorical_accuracy: 0.1289
Epoch 2/2000
8/8 [==============================] - 2s 235ms/step - loss: 2.1940 - categorical_accuracy: 0.2344
Epoch 3/2000
8/8 [==============================] - 2s 242ms/step - loss: 2.1720 - categorical_accuracy: 0.1367
Epoch 4/2000
8/8 [==============================] - 2s 229ms/step - loss: 2.1272 - categorical_accuracy: 0.1758
Epoch 5/2000
8/8 [==============================] - 2s 228ms/step - loss: 670.2028 - categorical_accuracy: 0.1719
Epoch 6/2000
8/8 [==============================] - 2s 242ms/step - loss: 114898.7344 - categorical_accuracy: 0.0898
Epoch 7/2000
8/8 [==============================] - 2s 239ms/step - loss: 3895200.5000 - categorical_accuracy: 0.1328
Epoch 8/2000
8/8 [==============================] - 2s 230ms/step - loss: 7626493.0000 - categorical_accuracy: 0.1172
Epoch 9/2000
8/8 [==============================] - 2s 253ms/step - loss: 6059563.000

KeyboardInterrupt: 

In [181]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_18 (LSTM)              (None, 60, 128)           198144    
                                                                 
 lstm_19 (LSTM)              (None, 60, 256)           394240    
                                                                 
 lstm_20 (LSTM)              (None, 128)               197120    
                                                                 
 dense_18 (Dense)            (None, 128)               16512     
                                                                 
 dense_19 (Dense)            (None, 64)                8256      
                                                                 
 dense_20 (Dense)            (None, 9)                 585       
                                                                 
Total params: 814,857
Trainable params: 814,857
Non-tr

# 8. Make Predictions

In [182]:
res = model.predict(X_test)

1/1 [==============================] - 0s 359ms/step


In [183]:
actions[np.argmax(res[4])]

'move_backword'

In [184]:
actions[np.argmax(y_test[4])]

'follow'

# 9. Save Weights

In [185]:
model.save('action.h5')

In [217]:
del model

In [186]:
model.load_weights('action.h5')

# 10. Evaluation using Confusion Matrix and Accuracy

In [187]:
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

In [188]:
yhat = model.predict(X_test)

1/1 [==============================] - 0s 43ms/step


In [189]:
ytrue = np.argmax(y_test, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()

In [190]:
multilabel_confusion_matrix(ytrue, yhat)

array([[[13,  0],
        [ 1,  0]],

       [[11,  0],
        [ 3,  0]],

       [[13,  0],
        [ 1,  0]],

       [[10,  0],
        [ 4,  0]],

       [[13,  0],
        [ 1,  0]],

       [[12,  0],
        [ 2,  0]],

       [[13,  0],
        [ 1,  0]],

       [[ 0, 13],
        [ 0,  1]]], dtype=int64)

In [191]:
accuracy_score(ytrue, yhat)

0.07142857142857142

# 11. Test in Real Time

In [19]:
from scipy import stats

In [20]:
colors = [(245,117,16), (117,245,16), (16,117,245)]
def prob_viz(res, actions, input_frame, colors):
    output_frame = input_frame.copy()
    for num, prob in enumerate(res):
        cv2.rectangle(output_frame, (0,60+num*40), (int(prob*100), 90+num*40), colors[num], -1)
        cv2.putText(output_frame, actions[num], (0, 85+num*40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
        
    return output_frame

In [21]:
plt.figure(figsize=(18,18))
plt.imshow(prob_viz(res, actions, image, colors))

NameError: name 'res' is not defined

<Figure size 1800x1800 with 0 Axes>

In [22]:
# 1. New detection variables
sequence = []
sentence = []
predictions = []
threshold = 0.5

cap = cv2.VideoCapture(3)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)
        
        # 2. Prediction logic
        keypoints = extract_keypoints(results)
        sequence.append(keypoints)
        sequence = sequence[-60:]
        
        if len(sequence) == 60:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
            print(actions[np.argmax(res)])
            predictions.append(np.argmax(res))
            
            
        #3. Viz logic
            if np.unique(predictions[-10:])[0]==np.argmax(res): 
                if res[np.argmax(res)] > threshold: 
                    
                    if len(sentence) > 0: 
                        if actions[np.argmax(res)] != sentence[-1]:
                            sentence.append(actions[np.argmax(res)])
                    else:
                        sentence.append(actions[np.argmax(res)])

            if len(sentence) > 5: 
                sentence = sentence[-5:]

            # Viz probabilities
            image = prob_viz(res, actions, image, colors)
            
        cv2.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
        cv2.putText(image, ' '.join(sentence), (3,30), 
                       cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
        
        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [200]:
cap.release()
cv2.destroyAllWindows()